config/routes.rb
UPCchat::Application.routes.draw do
  resources :messages
match "/messages/:from" => "messages#index"
root :to => "messages#index"

end

app/models/message.rb
class Message < ActiveRecord::Base

   attr_accessible :name, :content

  Pusher.app_id = '36097'
  Pusher.key = '5380f001a63bb1fa5e24'
  Pusher.secret = '43c4d689e27c00e69bd9'

  after_create :send_to_pusher

  def send_to_pusher
    logger.info "Hi?"
    Pusher['DEW2013'].trigger("message:create", self.to_json)


  end



  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
    @message = Message.new
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @messages }
    end
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
    @message = Message.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @message }
    end
  end

  # GET /messages/new
  # GET /messages/new.json
  def new
    @message = Message.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @message }
    end
  end

  # GET /messages/1/edit
  def edit
    @message = Message.find(params[:id])
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(params[:message])

    respond_to do |format|
      if @message.save
        format.html { redirect_to message_path(@message), notice: 'Message was successfully created.' }
        format.json { render json: @message, status: :created, location: @message }
      else
        format.html { render action: "new" }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /messages/1
  # PUT /messages/1.json
  def update
    @message = Message.find(params[:id])

    respond_to do |format|
      if @message.update_attributes(params[:message])
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message = Message.find(params[:id])
    @message.destroy

    respond_to do |format|
      format.html { redirect_to messages_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UPCchat</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <script src="http://js.pusher.com/1.12/pusher.min.js"></script>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/messages/_form.html.erb
<%= form_for(@message, :remote => true) do |f| %>
   <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<h1>Chat UPC</h1>


  <ul id="chat_container">
<% @messages.each do |message| %>
  
    <li><%= message.name %> dijo: <%= message.content %>
    </li>     
  
<% end %>
</ul>
<%= render 'form' %>

<script type="text/javascript">
  Pusher.log = function(message){
    if(window.console && window.console.log)window.console.log(message);

  };

  WEB_SOCKET_DEBUG = true;

  var pusher = new Pusher('5380f001a63bb1fa5e24')
  var channel = pusher.subscribe('DEW2013');

  channel.bind('message:create', function(data){
    var message = "<li id='message_"+ data.id +"'>"
        message += data.name+ ":"+data.content
        message += "</li>"

        $("#chat_container").append(message);
        $("#message_content").val("");
        $("#message_content").focus();


  });

</script>

app/views/messages/new.html.erb
<h1>New message</h1>

<%= render 'form' %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @message.name %>
</p>

<p>
  <b>Content:</b>
  <%= @message.content %>
</p>


<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>